version: '3'
services:
  dwm_status:
    build: dwm_status
    image: dwm_status
  firefox:
    build: firefox
    image: firefox
  offlineimap:
    build: offlineimap
    image: offlineimap
  ping:
    build: ping
    image: ping
  public_html:
    build: public_html
    image: public_html
  thunderbird:
    build: thunderbird
    image: thunderbird
  tmux:
    build:
      context: tmux
      args:
        image: dx-emulator-environment
    image: tmux
  xterm:
    build: xterm
    image: xterm
  ympd:
    build: ympd
    image: ympd
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    container_name: ympd
    volumes:
      - /var/lib/mpd/socket:/var/lib/mpd
    command: ympd -h /var/lib/mpd
  dtrace:
    build: dtrace
    image: dtrace
  key_presses:
    build: key_presses
    image: key_presses
    restart: unless-stopped
    container_name: key_presses
    volumes:
      - /var/run/key_presses/:/var/run/key_presses/
    devices:
      - /dev/dtrace
    depends_on:
      - dtrace
  media_keys:
    build: media_keys
    image: media_keys
    restart: unless-stopped
    container_name: media_keys
    volumes:
      - /home/robin/.mplayer:/mplayer
    devices:
      - /dev/dtrace
    depends_on:
      - dtrace

  graphite:
    build: graphite
    image: graphite
    restart: unless-stopped
    container_name: graphite
    ports:
      - "81:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
