#!/usr/bin/python2
import base64
import json
import sys

import paho.mqtt.client as mqtt

# This is the Publisher

client = mqtt.Client()
client.connect("mqtt", 1883, 60)

lines = sys.stdin.readlines()
if len(lines) == 0:
    title = 'No message'
    msg = ''
else:
    title = lines[0]
    msg = ''.join(lines[1:]).strip()

client.publish(
    sys.argv[1],
    json.dumps(
        {
            'width': 400,
            'height': 17,
            'timeout': 1,
            'title': base64.b64encode(title),
            'msg': base64.b64encode(msg)
        }
    )
)
client.disconnect();
